# Generated by Django 3.0.6 on 2020-05-14 12:16

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_todo_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='collaborators',
            field=jsonfield.fields.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
