# Generated by Django 3.0.6 on 2020-05-15 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_todo_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='colaborators',
            field=models.ForeignKey(blank=None, default=1, null=None, on_delete=django.db.models.deletion.CASCADE, related_name='colaborator', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
