# Generated by Django 3.0.6 on 2020-05-14 12:20

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_todo_collaborators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='collaborators',
            field=jsonfield.fields.JSONField(blank=True, default=[], null=True),
        ),
    ]
