# Generated by Django 3.0.6 on 2020-05-14 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_colloborator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colloborator',
            name='todo',
        ),
        migrations.AddField(
            model_name='colloborator',
            name='todo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Todo'),
        ),
    ]
