# Generated by Django 3.0.6 on 2020-05-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200515_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='colaborators',
        ),
    ]
