# Generated by Django 3.0.6 on 2020-05-15 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_auto_20200515_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collab',
            name='collaborators',
            field=models.ManyToManyField(blank=True, null=True, related_name='collaborators', to=settings.AUTH_USER_MODEL),
        ),
    ]
