# Generated by Django 3.0.6 on 2020-05-15 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200515_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborate',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='api.Todo'),
        ),
    ]
