# Generated by Django 3.0.6 on 2020-05-15 09:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_remove_todo_colaborators'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='colaborators',
            field=models.ManyToManyField(related_name='colaborators', to=settings.AUTH_USER_MODEL),
        ),
    ]
