# Generated by Django 3.0.6 on 2020-05-15 16:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_auto_20200515_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Collab',
        ),
    ]
