# Generated by Django 3.0.6 on 2020-05-15 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200515_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='collaborators',
            new_name='collab',
        ),
    ]
