# Generated by Django 3.0.6 on 2020-05-15 11:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_todo_colaborators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='colaborators',
            field=models.ManyToManyField(default=None, related_name='colaborators', to=settings.AUTH_USER_MODEL),
        ),
    ]
