# Generated by Django 3.0.6 on 2020-05-16 14:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_auto_20200516_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='collab',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
